name: TYNH
on:
  push:
    branches: [ develop ]
    tags: ['release-v*']
  workflow_dispatch:
jobs:
  build:
    needs: [clear-old-file]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Build source
        run: |
          npm install
          npm run build

      - name: Tansfer file to host
        run: |
          scp -i "${{ secrets.TENCENT_HOST_PRIVATE_KEY }}" -r ./dist/TYNH/* root@endingly.live:/home/app
          scp -i "${{ secrets.TENCENT_HOST_PRIVATE_KEY }}" -r ./src/app/server.js root@endingly.live:/home/app

  clear-old-file:
    name: clear
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }}
          script: |
            rm /home/app/*


