name: TYNH
on:
  push:
    branches: [ develop ]
    tags: ['release-v*']
  workflow_dispatch:
jobs:

  clear-old-file:
    name: clear
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }}
          script: |
            rm -r /home/app/*

  build_and_relase:
    needs: [clear-old-file]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Build source
        run: |
          npm install
          npm run build --prod

      # - name: upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: TYNH_relase
      #     path: |
      #       ./dist/TYNH
      #       ./src/app/server.js
      #     retention-days: 5

      - name: tansfer and release
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{secrets.HOST_USER}}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }} 
          local_path: './dist/TYNH/*'
          remote_path: '/home/app/'
      
      - name: tansfer and release second step
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{secrets.HOST_USER}}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }} 
          local_path: './src/app/server.js'
          remote_path: '/home/app/'
      


