name: TYNH
on:
  push:
    branches: [ develop ]
    tags: ['release-v*']
  workflow_dispatch:
jobs:
  build:
    needs: [clear-old-file]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Build source
        run: |
          npm install
          npm run build

      - name: Tansfer file to host
        run: |
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_1 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_2 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_3 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_4 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_5 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_6 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_7 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_8 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_9 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_10 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_11 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_12 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_13 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_14 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_15 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_16 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_17 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_18 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_19 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_20 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_21 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_22 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_23 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_24 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_25 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_26 }}' >> ./key
          echo '${{ secrets.TENCENT_HOST_PRIVATE_KEY_27 }}' >> ./key
          scp -i ./key -r ./dist/TYNH/* root@endingly.live:/home/app
          scp -i ./key -r ./src/app/server.js root@endingly.live:/home/app
          rm ./key

  clear-old-file:
    name: clear
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }}
          script: |
            rm -r /home/app/*


