name: TYNH
on:
  push:
    branches: [ develop ]
    tags: 'release-v*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Run build command
        run: |
          npm install
          npm build

      - name: Push Docker
        run: |
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password ${{ secrets.ALIYUN_PASSWORD }} registry.cn-shanghai.aliyuncs.com
          docker build . -t ${{ secrets.ALIYUN_REGISTRY }}:$GITHUB_RUN_NUMBER
          docker push ${{ secrets.ALIYUN_REGISTRY }}:$GITHUB_RUN_NUMBER
          docker tag $(docker images ${{ secrets.ALIYUN_REGISTRY }}:$GITHUB_RUN_NUMBER -q) ${{ secrets.ALIYUN_REGISTRY }}:latest
          docker push ${{ secrets.ALIYUN_REGISTRY }}:latest

  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.ALIYUN_REGISTRY }} -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.ALIYUN_REGISTRY }}:latest -q)
            docker rmi -f $(docker images  ${{ secrets.ALIYUN_REGISTRY }}:latest -q)
            docker login --username=${{ secrets.ALIYUN_USERNAME }} --password ${{ secrets.ALIYUN_PASSWORD }} registry.cn-shanghai.aliyuncs.com
            docker pull ${{ secrets.ALIYUN_REGISTRY }}:latest
            docker run -d -p 4200:4200 ${{ secrets.ALIYUN_REGISTRY }}:latest


